static char *hosts[] = { "ghc33.ghc.andrew.cmu.edu",
                       "ghc34.ghc.andrew.cmu.edu",
                       "ghc35.ghc.andrew.cmu.edu",
                       "ghc36.ghc.andrew.cmu.edu",
                       "ghc37.ghc.andrew.cmu.edu",
                       "ghc38.ghc.andrew.cmu.edu",
                       "ghc39.ghc.andrew.cmu.edu",
                       "ghc40.ghc.andrew.cmu.edu",
                       "ghc41.ghc.andrew.cmu.edu",
                       "ghc42.ghc.andrew.cmu.edu" };
