#!/bin/csh
@ i = 3
echo "--------Starting run--------" >> out.txt

while ($i <= 10)
  echo With $i processes
  echo $i processes  >> out.txt
  mpirun --prefix /usr/lib64/openmpi --mca btl_tcp_if_include eth0 --hostfile hosts -np $i -- ./tiny 24567 &
  sleep 2
  mpirun --prefix /usr/lib64/openmpi --mca btl_tcp_if_include eth0 --hostfile requesthosts -np 48 -- automate/auto ghc63.ghc.andrew.cmu.edu 24567 >> out.txt
  killall mpirun
  @ i += 1
end
